### ISSUE TITLE
Not bootable

### ISSUE THREAD

**Issue by ghost** [exynos-linux-stable/greatlte#1]
I sucessfully compiled this with 3 different toolchains, but when I flash it and try to boot, it stops half way through. Is this source bootable without changes?
From the logcat I could see that it ran for a bit before crashing and stops without any explicit error message.

**Comment by corsicanu** [comment]
Mind sharing some logs/kmsg? I'm compiling it myself now anyway.

**Comment by farovitus** [comment]
@BeatPlay Source is fine and bootable, check your ramdisk.  @corsicanu was able to boot the ELS fine on his device.
